version: 2
jobs:
  build:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - run:
          name: stable build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: test  
          command: cargo test