version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: stable build
          no_output_timeout: 3600
          command: |
            cargo build
      - run:
          name: test  
          command: cargo test