version: 2

jobs:
  build_and_test:
    docker:
      - image: rust:latest
    environment:
      - ROCKSDB_LIB_DIR: /usr/local/lib
      - SNAPPY_LIB_DIR: /usr/local/lib
      - RUSTFLAGS: -D warnings
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: echo 'export PATH=~/.cargo/bin:$PATH' >> $BASH_ENV
      - run: apt-get update
      - run: echo y | apt-get install libsnappy-dev
      - run: apt-get install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev
      - run: git clone https://github.com/facebook/rocksdb
      - run: cd rocksdb/ && make static_lib
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}
          paths:
            - $HOME/rocksdb
      - run: export ROCKSDB_LIB_DIR=$HOME/rocksdb
      - run: rustup show
      - run: env
      - run: cargo build
      - run: cargo test
      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}
          paths:
            - $HOME/.cargo
            - $HOME/.rustup
            - target

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
