[package]
name = "timestamp_service"
version = "0.1.0"
authors = ["ildar"]

[dependencies]
exonum = "0.6.0"
iron = "0.6.0"
bodyparser = "0.8.0"
router = "0.6.0"
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
exonum-time = "0.6.0"